# Sharpmake AppVeyor CI configuration

image: Visual Studio 2017

platform:
- Any CPU

configuration:
- Debug
- Release

before_build:
- cmd: bootstrap-sharpmake.bat
- cmd: nuget restore Sharpmake.sln

build:
  project: Sharpmake.sln
  verbosity: minimal

after_test:
- cmd: python regression_test.py

